### ISSUE TITLE
Create a new car screen

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#144]
Currently there is no way to add another car to the user's set of cars outside of the initial account setup. 

- [ ] Garage Screen
- [ ] Car Add/Edit Screen
- [ ] Car Details Screen

**Comment by baylessj** [comment]
## Info to display for each Car:
- Mileage
- Distance Rate
- Average Efficiency
- Name
- Photo?
- Make/Model/Year
- Last Completed Task

## Action Buttons
- C/U/D 

## General Info
- title: "Garage"

**Comment by DavBfr** [comment]
We need the VIN too

**Comment by baylessj** [comment]
![Garage](https://user-images.githubusercontent.com/16109996/77855618-80187480-71bf-11ea-993e-dbea1f53b9c0.png)
![Garage-_Car Details](https://user-images.githubusercontent.com/16109996/77855619-81e23800-71bf-11ea-96ed-43af227ca47e.png)
Figma mockups of the garage screen and details screen for a car. Tapping on a car's card will bring up the details screen

**Comment by DavBfr** [comment]
Looks good. No more drawer?

**Comment by baylessj** [comment]
I'd like to move away from it if possible, yeah. Most of that information should be able to go in the Garage tab, and the drawer is a bit of an uncomfortable reach for right-handed users

**Comment by DavBfr** [comment]
The garage tab should be the first icon then. I think the lighter color you used on the tabs background is better too.
