### ISSUE TITLE
Deploy 0.3.1 as com.autodo.autodo on official google account

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#264]
Need to move the app over to the autodoapp@gmail.com account and the app id will need to be updated in the firebase setup.

**Comment by DavBfr** [comment]
People using the internal database will not be able to migrate to the new application. Maybe we should upgrade the two versions in parallel. Do we have stats on how many use the firebase DB vs the internal DB?

**Comment by baylessj** [comment]
I don't know exactly how many users use the internal db unfortunately. I know that about half of the users who have downloaded the app have signed up with the firebase DB, but I don't know if the other users have actually opened the app or gotten set up with the internal DB.

At this point we don't have any users that are counting on auToDo as their main storage of car data, so I'm not really worried about the switch. Definitely don't want to make this transition in the future though.

**Comment by DavBfr** [comment]
Ads revenues are insignificant now. What do you think about keeping the app Ad-free until we reach 10k users? We can keep an in-app product as a bounty that could be bought multiple times.

**Comment by baylessj** [comment]
Sounds like a good plan to me. If you want to create a PR to set the Free Version State for the Paid Version Bloc to not show ads by default that would be great :+1:
