### ISSUE TITLE
Properly display ToDo names and status

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#268]
One of the more frequent comments I get about the screenshots is that the ToDo names look unfinished. Displaying these as something other than their camelCased backend names and including the right spacing between the status and the name will help the app look much better.

**Comment by DavBfr** [comment]
Yes, I thought it was done on purpose, to match "auToDo".
The platform notifications system has to be reworked for that, because it's all embedded into the BloC classes, which prevents any translation.

**Comment by baylessj** [comment]
The translation is done with keys, right? The current camelCase values could be set up as the keys for the translations and we'll display them that way

**Comment by DavBfr** [comment]
Yes, that was my plan.
