### ISSUE TITLE
Replace sembast with sqflite

### ISSUE THREAD

**Issue by DavBfr** [autodo-app/autodo#282]
The goal would be to use SQLite as the only data source for the application, and firebase or any other storage as a cloud backup but not as a main real-time data source.

**Comment by DavBfr** [comment]
Using an SQL database also helps migrating the backend form firebase to postgres or mysql #229

The Database would look like this:

## Car

Field | Type | Null | Key  | Default | Extra
----- | ---- | ---- | ---- | ------- | --------------
id    | int  | NO   | PRI  |         | auto_increment
name  | text | NO   | UNIQ |         |

## Refueling

Field    | Type     | Null | Key | Default | Extra
-------- | -------- | ---- | --- | ------- | -------------------
id       | int      | NO   | PRI |         | auto_increment
car      | int      | NO   |     |         | foreign key Car(id)
mileage  | num      | NO   |     |         |
date     | datetime | NO   |     |         |
amount   | num      | NO   |     |         |
cost     | num      | YES  |     |         |
currency | text     | YES  |     |         |

## Todo

Field            | Type     | Null | Key | Default | Extra
---------------- | -------- | ---- | --- | ------- | ----------------------
id               | int      | NO   | PRI |         | auto_increment
name             | text     |      |     |         |
car              | int      | NO   |     |         | foreign key Car(id)
repeat           | int      | YES  |     |         | foreign key Repeat(id)
dueState         | int      | NO   |     |         |
dueMileage       | num      | YES  |     |         |
notification     | int      | YES  |     |         |
completed        | int      | NO   | 0   |         | boolean
estimatedDueDate | datetime | YES  |     |         |
completedDate    | datetime | YES  |     |         |
dueDate          | datetime | YES  |     |         |

## Repeat

Field           | Type | Null | Key | Default | Extra
--------------- | ---- | ---- | --- | ------- | --------------
id              | int  | NO   | PRI |         | auto_increment
name            | text | NO   |     |
mileageInterval | int  |      |     |         | duration
dateInterval    | int  |      |     |         | duration

## RepeatCar

Field  | Type | Null | Key | Default | Extra
------ | ---- | ---- | --- | ------- | ----------------------
car    | int  | NO   | PRI |         | foreign key Car(id)
repeat | int  | NO   | PRI |         | foreign key Repeat(id)

**Comment by baylessj** [comment]
I like the database structure you laid out here, although we will probably want to combine the Todo and Repeat models per #275.

**Comment by DavBfr** [comment]
I stripped out everything from Car and Refueling that can be calculated. For Todo and Repeat, I'm still confused on how they work.

**Comment by DavBfr** [comment]
Here is a better DB schema:

![Screen Shot 2020-05-18 at 10 34 14](https://user-images.githubusercontent.com/1387855/82225524-5217fc80-98f3-11ea-8a0c-c4eae9daac44.png)

**Comment by warriorCoder** [comment]
Why the move away from noSql?
