### ISSUE TITLE
Create cohesive UI theme

### ISSUE THREAD

**Issue by baylessj** [autodo-app/autodo#304]
The addition of the Garage screen changed the feel of the UI on that page and the other screens need modified to fit with it. This would also be a good time to standardize on text styles and colors across the app.

**Comment by baylessj** [comment]
Originally a bullet point on #301

**Comment by baylessj** [comment]
![todos-screen-redo](https://user-images.githubusercontent.com/16109996/79401884-4d5cd300-7f58-11ea-9490-a916da55bb7f.png)
![refuelings-screen-redo](https://user-images.githubusercontent.com/16109996/79401882-4d5cd300-7f58-11ea-90d8-5e25a127562c.png)
![stats-screen-redo](https://user-images.githubusercontent.com/16109996/79401883-4d5cd300-7f58-11ea-9b38-4052bde58507.png)

Here are some mockups of a possible redesign of the other three screens to match the vibe of the Garage screen. Incorporates the same text and color styles between the screens and they have similar headers.

@DavBfr what are your thoughts on these mockups? Think they would be an improvement?

**Comment by baylessj** [comment]
I think this also relates to #314 where we're trying to make a more useful first tab with the most relevant information displayed. I think it would still be best to put an emphasis on the ToDo list tab since they will serve as reminders, and my hope for the Garage tab is that it would function a bit more as a settings menu that you don't access all that often. Hopefully the changes in the mockups above make the ToDos screen a better fit for the first tab than it currently is.

All of this is conjecture of course, and it would be good to keep an eye on the analytics data to see where users spend the most time. Whichever tab the users spend the most time should be the default IMO.

**Comment by DavBfr** [comment]
I like the content style for the Todos. The refueling could be improved: they look too much the same.

The Tab bar has a different color which is good, I would add a text below each icon. This way all is more obvious.

The top drawer style is strange and somehow disturbing with this reversed shadow.
What is the purpose of the top rectangular notch? It looks like it's to reveal something below.

On google maps, they use this kind of design but for secondary information displayed on top of the map. It can occupy the full screen or be totally hidden. It's the only app I can think of with this design, and it's not the part I prefer.

**Comment by baylessj** [comment]
I understand your concern with the bottom sheet style, it is a bit different than the norm. Perhaps removing the darker, "handle"-esque rectangle at the top of the sheet could help make it look more normal?

The trend is quite popular on Dribbble as of late, which is where I got the inspiration. A few examples here:
- https://dribbble.com/shots/8076106-Music-Streaming-App
- https://dribbble.com/shots/7315601-Mobile-Application-Watch-Your-Phone
- https://dribbble.com/shots/7191217-Banking-Mobile-App

Also your point on the refuelings is good, they tend to blend together a bit. I can try to increase the separation and/or difference between the items. One other potential option for this would be to show a calendar view instead of or in addition to the list view for the refuelings, that could be interesting.

**Comment by DavBfr** [comment]
I see. If it's not intended to be interactive that's fine. I also note that dribble has no reversed shadow. Which makes it just a header with a specific design.

**Comment by baylessj** [comment]
Yeah, removing the shadow should help make the design clearer. I'll add the updated refuelings screen on here when I figure out how I want to represent those.

**Comment by DavBfr** [comment]
maybe the full listview and header should be part of a SilverList/CustomScrollView
https://api.flutter.dev/flutter/widgets/SliverList-class.html
That's what I used for the Wizard screens

**Comment by baylessj** [comment]
That could work, I'll reference your Wizard screens as an example

**Comment by DavBfr** [comment]
The colors are deliberately garish.

![output](https://user-images.githubusercontent.com/1387855/79619326-8c1a9680-80da-11ea-843b-0523044f198f.gif)

**Comment by baylessj** [comment]
![refuelings-screen-redo-2](https://user-images.githubusercontent.com/16109996/79643029-f3822600-816e-11ea-9e26-fcc3d1b72d2e.png)

thoughts on this option?

**Comment by DavBfr** [comment]
I like it!
