### ISSUE TITLE
Put some default oil and tire change mileage removed in #311

### ISSUE THREAD

**Issue by DavBfr** [autodo-app/autodo#313]
Use the default values and add a screen to the wizard to choose the units if not already configured.

**Comment by baylessj** [comment]
Hi David, I'm not entirely sure what the error is here, can you please add some labels or additional description to this issue? I'm trying to clean up the list of issues and assign them to the appropriate project.

**Comment by DavBfr** [comment]
The default values are fine, but still, the first wizard screen should ask the user for his preferred units, especially for mules/kilometers as they will have to input some values on the next screens.
