### ISSUE TITLE
Required environment variables not provided

### ISSUE THREAD

**Issue by k4j8** [autodo-app/autodo#365]
What are the environment variables that need to be declared in the `.env` file? I was able to run the app with `docker-compose up -d`, but when I try to create a new user I simply get `{}` below the password and "Remember me" boxes. I'm assuming my blank `.env` file is the issue.

(I'm extremely excited by this project but have no experience with any of the technologies you're using besides Docker. I currently use a *very* elaborate Google Sheets file that tracks all of my maintenance intervals by time and by mileage, gas, fuel efficiency, cost per mile, tire wear, and miles driven, most being provided as a table and accompanying graph. It's not a good fit for a spreadsheet and I was looking at making a web app and then I found this. I don't know of *any* self-hosted alternatives, either.)

**Comment by baylessj** [comment]
Hi Kyle! 

Thanks for reaching out about this! I meant to keep a development `.env` file with the keys needed to run the app locally, but that didn't seem to make it into source control. I use the following contents in a `.env.dev` file:

```
DEBUG=1
SECRET_KEY=foo
DJANGO_ALLOWED_HOSTS=* localhost 127.0.0.1 [::1]
SQL_ENGINE=django.db.backends.postgresql
SQL_DATABASE=autodo_dev
SQL_USER=autodo
SQL_PASSWORD=autodo
SQL_HOST=db
SQL_PORT=5432
DATABASE=postgres
```

That being said, I've taken a break from this project over the last few months to work on other projects and hopefully come up with some ideas for making this a viable app. I started auToDo with a vision of a huge cross-platform app and got bogged down by it before making it work decently on any one platform. There's a start here for a mobile app, web app, API, homepage, and blog. None of them are really working at the moment, and I need to focus on one at a time and getting an MVP going. All of this to say, auToDo in its current state won't work for you even with the environment variables set up right. 

I also have a Google Sheets file that I'm using in the interim to track these sorts of tasks. It's fairly simple though, so I would appreciate hearing more about how you have your sheet set up. The current auToDo prototype is designed with my workflow in mind and I'd like to eventually make it a design that works for more people

I'm wrapping up another side project at the moment but I'd like to take another shot at making auToDo work in the next couple weeks. The first order of business with that will be paring down the big mess of functionality that exists in the project now and set up a plan for making a smaller, working, v2. If you're interested in helping identify that subset of functionality for auToDo v2 I would be glad to have your input!

**Comment by k4j8** [comment]
Thanks for the detail, I'll at least take a look at it. I'd like to help, but I'm brand new to web development and it will take me a while to wrap my head around this project. Good luck!
